apiVersion: apps/v1
kind: Deployment
metadata:
  name: hash-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hash-service
  template:
    metadata:
      labels:
        app: hash-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: hash-service
          image: hash-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
            # - containerPort: 9464
          envFrom:
            - configMapRef:
                name: hash-service-config
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
